### ISSUE TITLE
Android app missing

### ISSUE THREAD

**Issue by CVasilakis** [danjulio/tCam#11]
In the [readme.md](https://github.com/danjulio/tCam/blob/main/readme.md) it is written that an [Android App](https://play.google.com/store/apps/details?id=com.darcangel.tcamViewer) exist but there is no such app on google play store.
Moreover the [repo](https://github.com/yaturner/tcamViewer) mentioned on the same paragraph does not exist either.

**Comment by djpinkbunny** [comment]
https://play.google.com/store/search?q=Tcamviewer&c=apps&gl=US
