### ISSUE TITLE
Windows Desktop App - Discovery of Camera not working on my system.

### ISSUE THREAD

**Issue by malansk** [danjulio/tCam#12]
With the default configuration of the tcam-mini as Access Point, I can connect to the camera and change "Camera Settings / WiFi" to disable AP mode and set SSID and PW of my WiFi network.

"Preferences / Discover" in the Windows Desktop App however does not find a camera (the small circle animation runs for approx. 12s but no result).

I have "Bonjour" installed and also tried the provided "Bonjour SDK" as well as running the Desktop App in Administrator mode to no avail.

If look in my routers network device list for the ESPRESSIF device IP address and put that manually in the app then the camera is working.

By the way, the Android app is able to discover the camera.

**Comment by danjulio** [comment]
Sorry you're having this trouble.  Are you running Windows 11?  I did some googling and it appears something Windows 11 does stops Bonjour.  I am no expert in anything windows but maybe start up Services and look to see if Bonjour is running.  According to the links I read you might be able to start it there.  Here are a couple of pages in Microsoft forums that talk about this

https://answers.microsoft.com/en-us/windows/forum/all/bonjour-service-being-disabled-and-not-starting-in/503b37b8-5146-4339-9418-74e7a81e7e72

https://answers.microsoft.com/en-us/windows/forum/all/windows-11-disabling-bonjour/4e6a8a12-a715-46c2-8ce6-1eaef57da888

If it does have to do with some incompatibility with Windows 11 then, unfortunately, there is probably little I - a lowly app developer, caught between titans - can do to fix this.  Sorry I don't have a better answer.  Let me know what you find in Services.

**Comment by malansk** [comment]
Im am running Microsoft Windows [Version 10.0.19045.4412]
Windows 10 Home 64-Bit Version running on Intel i7-6700 with 8GB Ram 
I will look for the service status in a few days when I'm back at home.

**Comment by malansk** [comment]
I can confirm it was an issue with the Bonjour Service, after Restart Discovery was working.
