### ISSUE TITLE
Lepton CCI communication failed (I2C interface)

### ISSUE THREAD

**Issue by alejandrolri** [danjulio/tCam#3]
I´m getting 4 red blinks in my tCam-mini which means Lepton CCI communication failed (I2C interface). How can I fix this issue?

**Comment by danjulio** [comment]
Probably the Lepton is loose in the socket.  Very carefully press it down into the socket.  You should hear a click as it settles into place.  If this does not work then attach the camera to a serial monitor (Arduino Serial Monitor, CoolTerm, screen or the like) at 115200 and copy the start-up log information here for me to debug.

**Comment by alejandrolri** [comment]
The Lepton is loose. Problem solved. Thank you.
