### ISSUE TITLE
Enclosure errors

### ISSUE THREAD

**Issue by zharijs** [danjulio/tCam#8]
tCam-mini v4 boards from Digikey does not fit the enclosure correctly. Both - USB connector and sensor holes have a gross offset.

**Comment by danjulio** [comment]
What specific STL files did you use?  There are files also for the v2 boards and Zeke's enclosure was also for v2.  The v4 files have been printed successfully quite a lot...

**Comment by zharijs** [comment]
I made my own, but took these as base for hole locations:
https://github.com/danjulio/tCam/tree/main/tCam-Mini/enclosure/tcam_mini_basic/tcam_mini_basic

To be honest, I might have used the "bezel" file in 180 degree rotation. Not sure about that. But still, USB hole seems to be 1mm offset. 

Anyway - you can add link or just copy my files to your repo. Just tested - all holes in place and it's GoPro compatible. Also has STEP and original Rhino project:

https://github.com/zharijs/Enclosures/tree/main/tCam%20enclosure

H.

**Comment by danjulio** [comment]
Harry,

I finally had a minute and I updated the repo and hackaday.io project entry to show off your fantastic enclosures and give you a shout-out.  Much better than mine.  Thank you so much for sharing these.

Regards, Dan

**Comment by zharijs** [comment]
Glad to give back to community :)
