### ISSUE TITLE
Android app not available

### ISSUE THREAD

**Issue by Bill-CRM** [danjulio/tCam#9]
It seems google removed the app from play store, and the alterate link is not working too.

**Comment by dudeitssm** [comment]
Appears his repo was removed for some reason, and his domain registration ran out.

I have downloaded the alpha version from his other repo, which is still up.
https://github.com/yaturner/tcamViewerRelease

```
$ sha256sum tcamViewer_release_v0.3.6.apk 
7049e02947714c63156992781de922b2fb8138b2e0f8263ff776d4de12f3767d  tcamViewer_release_v0.3.6.apk
```

I have also submitted the repo URL to Archive.org for preservation.

[Here's an Archive capture](https://web.archive.org/web/20230518034318/https://play.google.com/store/apps/details?id=com.darcangel.tcamViewer) of the Google Play URL.

I'm sure there is someone out there with the APK who would be willing to reupload it and also provide a SHA256 checksum for those of us obtaining it from other locations to verify file integrity.

**Comment by Bill-CRM** [comment]
Thanks, I will try it out.

**Comment by danjulio** [comment]
I have mentioned this to the author and he is looking into it.  Apparently there was a credit card expired issue which lead to a bunch of problems.

Good news for you all is that the version 1.0 app is going to be posted and it has new features including video export.

**Comment by McGeaverBeaver** [comment]
Hey @danjulio  any updates to this? I see the github for the author is as well removed? is the project dead? any chance we can get the code from a repo for someone else to pickup?
